stages:
  - test

variables:
  PYTHONPATH: "."

pytest:
  stage: test
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - sudo apt-get install ncbi-blast+ hmmer
  script:
    - pytest
